version: 0.1

environment_variables:
  plaintext:
    AWS_REGION: "us-west-2"
    AWS_DELAY: "10000"
    AWS_DEPLOY_TIMEOUT: "20000"
    AWS_DEPLOY_RETRIES: "10"
    TEST_TIMEOUT: "150000"

phases:
  install:
    commands:
      - echo "NODE VERSION"
      - node --version
      - echo "NPM VERSION"
      - npm --version
      - npm install --no-audit --silent 
  build:
    commands:
      - npm test -- ci > buildresult.txt 

artifacts:
  files:
    - buildresult.txt
  discard-paths: yes
